apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd-run
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tawfiqh58/k8s-argocd
    targetRevision: HEAD
    path: infra/k8s
  destination: 
    server: https://kubernetes.default.svc
    namespace: dev-namespace
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
