apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-server-depl
  labels:
    app.kubernetes.io/name: express-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: express-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: express-server
    spec:
      containers:
        - name: express-container
          image: tawfiq58/express-server
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: express-server-lb
spec:
  selector:
    app.kubernetes.io/name: express-server
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 5000
