apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-depl
  labels:
    app.kubernetes.io/name: reactapp
spec:
  replicas: 100
  selector:
    matchLabels:
      app.kubernetes.io/name: reactapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reactapp
    spec:
      containers:
        - name: reactapp-container
          image: registry.digitalocean.com/th58-dockerimage/reactapp:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: digitalocean-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-lb
spec:
  selector:
    app.kubernetes.io/name: reactapp
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
